### PR TITLE
Update to scikit-umfpack 0.2.2

### PR DESCRIPTION
**Pull request by cmutel**
- Patches are deleted, as these changes are now in the latest release.
- Download URL is updated, as current URL returns a 301 status code.

### CODE REVIEW

**Comment by pelson** [comment]
> Patches are deleted, as these changes are now in the latest release.

That is awesome news! Definitely how patches should be used within conda-forge. :tada:

**Comment by grlee77** [comment]
Thanks @cmutel.  Please also add yourself to the maintainers list in meta.yaml if you would like.  I have been traveling this week and haven't had a chance to check why the Circle build failed here.

I will restart the Travis build later if it gets canceled.  They were having some problems yesterday at the time this was submitted.

**Comment by grlee77** [comment]
The import error seems to be caused by a missing `scikits/__init__.py`.  This file does not appear to exist within the linked release 0.2.2 `.tar.gz`.  Is this maybe an error in packaging the source for pypi?

**Comment by cmutel** [comment]
[Reported](https://github.com/scikit-umfpack/scikit-umfpack/issues/28). @rc is normally super-responsive, so should be fixed soon.

**Comment by cmutel** [comment]
Updated PR passes all tests; missing `__init__` was added in 0.2.3.

**Comment by jakirkham** [comment]
LGTM

**Comment by grlee77** [comment]
Thanks @cmutel

**Comment by jakirkham** [comment]
The Python 3.5, NumPy 1.11.x build hung while removing Homebrew stuff. Not sure why. I went ahead and restarted it. Keep an eye on it.

**Comment by grlee77** [comment]
Looks like it went through now.  Thanks @jakirkham

**Pull request merged**
