### PR TITLE
Build for osx_arm64, win_64, linux_64, linux_ppc64le, linux_aarch64 (PR #30)

### PR DESCRIPTION
**Pull request by michaelweinold**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by michaelweinold** [comment]
Currently using my own fork of scikit-umfpack with a new release (0.3.3):

```
{% set version = "0.3.3" %}
source:
  git_url: https://github.com/michaelweinold/scikit-umfpack
  git_tag: {{ version }}
```

Should be updated to point to scikit-umfpack/scikit-umfpack/ before merging.

**Comment by michaelweinold** [comment]
Fixes https://github.com/conda-forge/scikit-umfpack-feedstock/pull/30#issuecomment-1203886199 and https://github.com/conda-forge/scikit-umfpack-feedstock/pull/30#issuecomment-1203916284.

**Comment by michaelweinold** [comment]
```
2022-08-04T13:39:42.2829760Z error: Command "arm64-apple-darwin20.0.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem 

(...)

/include/python3.8 -c build/src.macosx-11.0-arm64-3.8/scikits/umfpack/_umfpack_wrap.c -o build/temp.macosx-11.0-arm64-cpython-38/build/src.macosx-11.0-arm64-3.8/scikits/umfpack/_umfpack_wrap.o -MMD -MF build/temp.macosx-11.0-arm64-cpython-38/build/src.macosx-11.0-arm64-3.8/scikits/umfpack/_umfpack_wrap.o.d -faltivec -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
```

NumPy 1.19.X has issues with ARM64 architecture. Compare https://github.com/numpy/numpy/issues/17807 and this [StackOverflow question](https://stackoverflow.com/q/65336789/).

**Comment by michaelweinold** [comment]
Changed source from GitHub fork to PyPI now that 0.3.3 of scikit-umfpack has been released, as per https://github.com/scikit-umfpack/scikit-umfpack/issues/72#issuecomment-1205298388.

**Comment by cmutel** [comment]
First build is 0, not 1

**Comment by cmutel** [comment]
Please update recipe YAML to:
```
about:
    license: BSD-3-Clause
```

**Comment by cmutel** [comment]
As far as I can understand, here is the problem with the numpy 1.19 builds on MacOS:

They both include an extra flag in the clang command: `extra options: '-faltivec -I/System/Library/Frameworks/vecLib.framework/Headers'`. The problem is the `altivec` flag, which is problematic for two reaasons:

1. `clang-13: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly`
2. ARM processes don't include the [altivec](https://en.wikipedia.org/wiki/AltiVec) SIMD instruction set.

The 1.21 build just omits the `altivec` flag: `extra options: '-I/System/Library/Frameworks/vecLib.framework/Headers'`.

The x64 uses x64 SSE3 SIMD instructions: `extra options: '-msse3 -I/System/Library/Frameworks/vecLib.framework/Headers'`.

I don't see any way to change this flag, and looking in things like the numpy feedstock didn't help.

Maybe we can just delete the failing configs in `.ci_support` and adjust `.azure-pipelines/azure-pipelines-osx.yml`?

**Comment by michaelweinold** [comment]
I agree with @cmutel: NumPy 1.19 has well documented issues with ARM architecture (as documented earlier, compare https://github.com/conda-forge/scikit-umfpack-feedstock/pull/32#issuecomment-1205296094). Removing all build configs that use NumPy 1.19.

**Pull request merged**
